Fix microversion compatibility issue for OpenStack Baremetal API
CCI-MOC/python-esiclient pull request #70
Opened 2024-12-16 14:00 UTC by skanthed

2024-12-16 14:09 UTC, skanthed commented
@tzumainn I’m unable to select you as reviewer to this PR directly. Could you please check if I can be given the necessary permissions to do so for this repo?

2024-12-16 15:54 UTC, tzumainn commented
Ah,  I don't think this is the change we need - first, I think our version of Ironic doesn't go up to 1.72; second, the core issue is that the version set there isn't being passed into the call to Ironic; I suspect something needs to be set in the esisdk. Make sure you test in a clean python environment, first verifying that if you unset `OS_BAREMETAL_API_VERSION` then a command like `openstack esi node network list` will fail; then verifying it passes with whatever changes you make!

2025-01-16 22:05 UTC, larsks requested changes
I agree with Mainn's comment; just marking this reviewed so I don't get reminders for it.

2025-02-07 19:42 UTC, joachimweyl commented
@skanthed what are the next steps?

2025-03-31 21:22 UTC, closed without merging